# Generated by Django 5.1 on 2024-09-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('titleName', models.CharField(max_length=60)),
                ('hasPassport', models.BooleanField()),
                ('salary', models.FloatField()),
                ('birthDate', models.DateField()),
                ('hireDate', models.DateField()),
                ('age', models.IntegerField(default=None)),
                ('country', models.CharField(default='', max_length=60)),
                ('dept', models.CharField(default='', max_length=60)),
                ('email', models.EmailField(default=None, max_length=100)),
                ('phoneNumber', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
